### ISSUE TITLE
[8.0] base_exports_manager - Cambio de nombre y error el bugtracker

### ISSUE THREAD

**Issue by rafaelbn** [Antiun/antiun-odoo-addons#6]
@antespi 

base_exports_manager
8.0

@pedrobaeza recomienda cambiar el nombre a base_export_manager (sin s en export)

Además al querer abrir un issue con el bugtracker no me lo crea en nuestro repo, me lleva aquí (debe de estar mal la plantilla o habéis hecho un PR):

https://github.com/OCA/server-tools/issues/new

**Comment by pedrobaeza** [comment]
No, recomiendo cambiarlo a _base_export_extension_ (sin s y cambiando manager por extension).

**Comment by rafaelbn** [comment]
@pedrobaeza va a ser un Gestor no una Extensión. A priori será un gestor de listas de exportación para el admin, pero puede ser planteado para los usuarios también.

**Comment by pedrobaeza** [comment]
Lo que habeis hecho la convierte en una extension (mostrar ese campo). Otra extensión será ese gestor que comentas.

**Comment by rafaelbn** [comment]
@pedrobaeza el campo sólo se muestras si estás en modo desarrollador.

**Comment by pedrobaeza** [comment]
Bueno, pero es una extensión. Yo lo dejaría con ese nombre. Luego, haced lo que queráis. Si acaso, hay que ponerlo apellido: _base_export_loquehaga_manager_, pero desde luego, no lo otro, y el plural hay que tratar de evitarlo siempre.

**Comment by rafaelbn** [comment]
@antespi toma nota

**Comment by rafaelbn** [comment]
cc @antespi

**Comment by rafaelbn** [comment]
@JavierIniesta ¿Cómo está esto? podemos cerrar issue?

**Comment by JavierIniesta** [comment]
Es la primera noticia que tengo al respecto. De hecho, el PR a OCA/server tools está hecho con el nombre base_exports_manager

**Comment by rafaelbn** [comment]
PR en OCA: https://github.com/OCA/server-tools/pull/289 (siempre debemos referenciar)

**Comment by rafaelbn** [comment]
Ya está el módulo en OCA
